services:
  - type: web
    name: regionwebllc
    env: python
    repo: https://github.com/rgnwebllc/regionwebllc.git
    branch: main  # or 'master' if that's your default branch
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate && python manage.py collectstatic --noinput && gunicorn website.wsgi:application
    buildFilter:
      paths:
        - website/*
        - templates/*
        - static/*
        - manage.py