databases:
  - name: regionwebllc-db
    plan: starter
    databaseName: regionwebllc
    user: regionwebllc_user

services:
  - type: web
    name: regionwebllc
    env: python
    repo: https://github.com/rgnwebllc/regionwebllc.git
    branch: main
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate --noinput && \
      python manage.py collectstatic --noinput && \
      gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: regionwebllc-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: regionwebllc.onrender.com,www.regionwebllc.com,regionwebllc.com
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: DISCORD_LOG_TOKEN
        sync: false
      - key: SENDGRID_API_KEY
        sync: false

  - type: worker
    name: discord-crm-bot
    env: python
    repo: https://github.com/rgnwebllc/regionwebllc.git
    branch: main
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python bot.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DJANGO_WEBHOOK_URL
        value: https://www.regionwebllc.com/api/update-lead-status/
      - key: DISCORD_LOG_TOKEN
        sync: false