services:
  - type: web
    name: regionwebllc
    env: python
    repo: https://github.com/rgnwebllc/regionwebllc.git
    branch: main  # or 'master' if that's your default branch
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py collectstatic --noinput && \
      gunicorn config.wsgi:application
    envVars:
    - key: DJANGO_SETTINGS_MODULE
      value: config.settings
    - key: SECRET_KEY
      sync: false
    - key: DEBUG
      value: "False"
    - key: ALLOWED_HOSTS
      value: regionwebllc.onrender.com
    buildFilter:
      paths:
        - website/*
        - templates/*
        - static/*
        - manage.py