# Generated by Django 5.2 on 2025-05-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='phone',
        ),
        migrations.AddField(
            model_name='lead',
            name='budget',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='business',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
