# Generated by Django 5.2 on 2025-05-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/avatar.png', upload_to='profile_pics/'),
        ),
    ]
