# Generated by Django 5.2 on 2025-05-06 04:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_subscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
