# Generated by Django 5.2 on 2025-05-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('no plan currently selected.', 'No plan currently selected.'), ('monthly', 'Monthly'), ('semi-annual', 'Semi-Annual'), ('annual', 'Annual')], max_length=50),
        ),
    ]
