# Generated by Django 5.2 on 2025-05-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='previous_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
