# Generated by Django 5.2 on 2025-05-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_subscription_previous_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='previous_plan',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('semi-annual', 'Semi-Annual'), ('annual', 'Annual')], max_length=50),
        ),
    ]
